config/routes.rb
Rails.application.routes.draw do
  root to: 'papers#index'
  resources :authors
  resources :papers
  resources :publications
  resources :publishers
  resources :keywords
  resources :locales
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/names_extension.rb
module NamesExtension

  def build_blanks
    locale_keys = Locale.pluck(:value) - pluck(:locale)
    build(locale_keys.map { |locale_key| { locale: locale_key } })
  end

  def mark_blanks_for_destruction
    select { |name| name.value.blank? }.each do |name|
      name.mark_for_destruction
    end
  end

end

app/models/locale.rb
class Locale < ApplicationRecord
  validates :value,
    uniqueness: true,
    presence: true
end

app/models/publisher.rb
class Publisher < ApplicationRecord

  has_many :names,
    -> { where(namable_scope: :name) },
    class_name: Name.to_s,
    as: :namable,
    extend: NamesExtension
  has_many :abbreviations,
    -> { where(namable_scope: :abbreviation) },
    class_name: Name.to_s,
    as: :namable,
    extend: NamesExtension

  accepts_nested_attributes_for :names
  accepts_nested_attributes_for :abbreviations

  after_initialize do
    names.build_blanks
    abbreviations.build_blanks
  end

  before_validation do
    names.mark_blanks_for_destruction
    abbreviations.mark_blanks_for_destruction
  end

  validates :names,
    length: {
      minimum: 1
    }
  validates :url,
    url: { allow_nil: true }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locales_controller.rb
class LocalesController < ApplicationController

  before_action :set_locale, only: [:show, :edit, :update, :destroy]

  # GET /locales
  def index
    @locales = Locale.all
  end

  # GET /locales/1
  def show
  end

  # GET /locales/new
  def new
    @locale = Locale.new
  end

  # GET /locales/1/edit
  def edit
  end

  # POST /locales
  def create
    @locale = Locale.new(locale_params)
    if @locale.save
      redirect_to @locale, notice: 'Locale was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /locales/1
  def update
    if @locale.update(locale_params)
      redirect_to @locale, notice: 'Locale was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /locales/1
  def destroy
    @locale.destroy
    redirect_to locales_url, notice: 'Locale was successfully destroyed.'
  end

  private

    def set_locale
      @locale = Locale.find(params[:id])
    end

    def locale_params
      params.require(:locale).permit(:value)
    end

  end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController

  before_action :set_publisher, only: [:show, :edit, :update, :destroy]

  # GET /publishers
  def index
    @publishers = Publisher.all.decorate
  end

  # GET /publishers/1
  def show
  end

  # GET /publishers/new
  def new
    @publisher = Publisher.new.decorate
  end

  # GET /publishers/1/edit
  def edit
  end

  # POST /publishers
  def create
    @publisher = Publisher.new(publisher_params)
    if @publisher.save
      redirect_to @publisher, notice: "Publisher was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /publishers/1
  def update
    if @publisher.update(publisher_params)
      redirect_to @publisher, notice: "Publisher was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /publishers/1
  def destroy
    @publisher.destroy
    redirect_to publishers_url, notice: "Publisher was successfully destroyed."
  end

  private

  def set_publisher
    @publisher = Publisher.find(params[:id]).decorate
  end

  def publisher_params
    params.require(:publisher).permit(
      :url,
      names_attributes: [:id, :locale, :value],
      abbreviations_attributes: [:id, :locale, :value]
    ).tap { |it|
      it.compact_blank!
      it[:names_attributes]&.reject! { |key, value|
        value[:id].blank? && value[:value].blank?
      }
      it[:abbreviations_attributes]&.reject! { |key, value|
        value[:id].blank? && value[:value].blank?
      }
    }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CV</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>
  <body>
  <nav class="navbar navbar-expand-sm navbar-light bg-light">
    <div class="container-fluid">
      <%= link_to 'CV', root_path, class: %w[navbar-brand] %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'Papers', papers_path, class: %w[nav-link] %>
          </li>
          <li class="nav-item">
            <%= link_to 'Authors', authors_path, class: %w[nav-link] %>
          </li>
          <li class="nav-item">
            <%= link_to 'Publications', publications_path, class: %w[nav-link] %>
          </li>
          <li class="nav-item">
            <%= link_to 'Publishers', publishers_path, class: %w[nav-link] %>
          </li>
          <li class="nav-item">
            <%= link_to 'Keywords', keywords_path, class: %w[nav-link] %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
    <div class="container mt-3">
      <%= yield %>
    </div>
  </body>
</html>

app/views/locales/_form.html.erb
<%= form_with(model: locale) do |form| %>
  <% if locale.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <p><%= pluralize(locale.errors.count, "error") %> prohibited this locale from being saved:</p>
      <ul>
        <% locale.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="btn-toolbar mb-3" role="toolbar">
    <div class="btn-group me-auto" role="group">
      <%= link_to locale, class: %w[btn btn-light] do %>
        <i class="bi bi-arrow-left-short"></i>
        <span>Back</span>
      <% end %>
    </div>
    <div class="btn-group ms-auto" role="group">
      <%= form.submit class: %w[btn btn-primary] %>
    </div>
  </div>
  <div class="mb-3 row">
    <div class="col-sm-2">
      <%= form.label :value, class: %w[col-form-label] %>
    </div>
    <div class="col-sm-10">
      <%= form.text_field :value, class: %w[form-control] %>
    </div>
  </div>
<% end %>

app/views/locales/edit.html.erb
<nav>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to "Locales", locales_path %>
    </li>
    <li class="breadcrumb-item">
      <%= link_to @locale.id, @locale %>
    </li>
    <li class="breadcrumb-item active">
      <span>Editing</span>
    </li>
  </ol>
</nav>
<%= render "form", locale: @locale %>

app/views/locales/index.html.erb
<% if notice.present? %>
  <div class="alert alert-info" role="alert">
    <%= notice %>
  </div>
<% end %>
<nav>
  <ol class="breadcrumb">
    <li class="breadcrumb-item active">Locales</li>
  </ol>
</nav>
<div class="btn-toolbar mb-3" role="toolbar">
  <div class="btn-group ms-auto" role="group">
    <%= link_to "New Locale", new_locale_path, class: %w[btn btn-primary] %>
  </div>
</div>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Value</th>
      </tr>
    </thead>
    <tbody>
      <% @locales.each do |locale| %>
        <tr>
          <td><%= link_to locale.value, locale %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/locales/new.html.erb
<nav>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to "Locales", locales_path %>
    </li>
    <li class="breadcrumb-item active">
      <span>New</span>
    </li>
  </ol>
</nav>
<%= render "form", locale: @locale %>

app/views/locales/show.html.erb
<% if notice.present? %>
  <div class="alert alert-info" role="alert">
    <%= notice %>
  </div>
<% end %>
<nav>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to "Locales", locales_path %>
    </li>
    <li class="breadcrumb-item active">
      <%= @locale.id %>
    </li>
  </ol>
</nav>
<div class="btn-toolbar mb-3" role="toolbar">
  <div class="btn-group me-auto" role="group">
    <%= link_to locales_path, class: %w[btn btn-light] do %>
      <i class="bi bi-arrow-left-short"></i>
      <span>Back</span>
    <% end %>
  </div>
  <div class="btn-group ms-auto" role="group">
    <%= link_to "Edit", edit_locale_path(@locale), class: %w[btn btn-primary] %>
  </div>
  <div class="btn-group ms-2" role="group">
    <%= link_to @locale, method: :delete, class: %w[btn btn-danger],
        data: { confirm: "Are you sure?" } do %>
      <i class="bi bi-trash"></i>
      <span>Destroy</span>
    <% end %>
  </div>
</div>
<div class="mb-3 row">
  <label class="col-sm-2 col-form-label">Value</label>
  <div class="col-sm-10">
    <span class="form-control-plaintext">
      <%= @locale.value %>
    </span>
  </div>
</div>

app/views/publishers/_form.html.erb
<%= form_with(model: publisher) do |form| %>
  <% if publisher.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <p><%= pluralize(publisher.errors.count, "error") %> prohibited this publisher from being saved:</p>
      <ul>
        <% publisher.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="btn-toolbar mb-3" role="toolbar">
    <div class="btn-group me-auto" role="group">
      <%= link_to publisher, class: %w[btn btn-light] do %>
        <i class="bi bi-arrow-left-short"></i>
        <span>Back</span>
      <% end %>
    </div>
    <div class="btn-group ms-auto" role="group">
      <%= form.submit class: %w[btn btn-primary] %>
    </div>
  </div>
  <%= form.fields_for :names do |names| %>
    <div class="mb-3 row">
      <div class="col-sm-2">
        <%= names.label :value, class: %w[col-form-label] do %>
          <%= tag.span(I18n.t(:name, locale_key: names.object.locale,
            scope: [:activerecord, :attributes, :publisher])) %>
        <% end %>
      </div>
      <div class="col-sm-10">
        <%= names.hidden_field :locale %>
        <%= names.text_field :value, class: %w[form-control] %>
      </div>
    </div>
  <% end %>
  <%= form.fields_for :abbreviations do |abbreviations| %>
    <div class="mb-3 row">
      <div class="col-sm-2">
        <%= abbreviations.label :value, class: %w[col-form-label] do %>
          <%= tag.span(I18n.t(:abbreviation, locale_key: abbreviations.object.locale,
            scope: [:activerecord, :attributes, :publisher])) %>
        <% end %>
      </div>
      <div class="col-sm-10">
        <%= abbreviations.hidden_field :locale %>
        <%= abbreviations.text_field :value, class: %w[form-control] %>
      </div>
    </div>
  <% end %>
  <div class="mb-3 row">
    <div class="col-sm-2">
      <%= form.label :url, class: %w[col-form-label] %>
    </div>
    <div class="col-sm-10">
      <%= form.text_field :url, class: %w[form-control] %>
    </div>
  </div>
<% end %>

app/views/publishers/edit.html.erb
<nav>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to "Publishers", publishers_path %>
    </li>
    <li class="breadcrumb-item">
      <%= link_to @publisher.id, @publisher %>
    </li>
    <li class="breadcrumb-item active">
      <span>Editing</span>
    </li>
  </ol>
</nav>
<%= render "form", publisher: @publisher %>

app/views/publishers/index.html.erb
<% if notice.present? %>
  <div class="alert alert-info" role="alert">
    <%= notice %>
  </div>
<% end %>
<nav>
  <ol class="breadcrumb">
    <li class="breadcrumb-item active">Publishers</li>
  </ol>
</nav>
<div class="btn-toolbar mb-3" role="toolbar">
  <div class="btn-group ms-auto" role="group">
    <%= link_to "New Publisher", new_publisher_path, class: %w[btn btn-primary] %>
  </div>
</div>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Abbreviation</th>
        <th>URL</th>
      </tr>
    </thead>
    <tbody>
      <% @publishers.each do |publisher| %>
        <tr>
          <td><%= link_to publisher.names_tag, publisher %></td>
          <td><%= publisher.abbreviations_tag %></td>
          <td><%= publisher.link_to_url_tag %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/publishers/new.html.erb
<nav>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to "Publishers", publishers_path %>
    </li>
    <li class="breadcrumb-item active">
      <span>New</span>
    </li>
  </ol>
</nav>
<%= render "form", publisher: @publisher %>

app/views/publishers/show.html.erb
<% if notice.present? %>
  <div class="alert alert-info" role="alert">
    <%= notice %>
  </div>
<% end %>
<nav>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to "Publishers", publishers_path %>
    </li>
    <li class="breadcrumb-item active">
      <%= @publisher.id %>
    </li>
  </ol>
</nav>
<div class="btn-toolbar mb-3" role="toolbar">
  <div class="btn-group me-auto" role="group">
    <%= link_to publishers_path, class: %w[btn btn-light] do %>
      <i class="bi bi-arrow-left-short"></i>
      <span>Back</span>
    <% end %>
  </div>
  <div class="btn-group ms-auto" role="group">
    <%= link_to "Edit", edit_publisher_path(@publisher), class: %w[btn btn-primary] %>
  </div>
  <div class="btn-group ms-2" role="group">
    <%= link_to @publisher, method: :delete, class: %w[btn btn-danger],
        data: { confirm: "Are you sure?" } do %>
      <i class="bi bi-trash"></i>
      <span>Destroy</span>
    <% end %>
  </div>
</div>
<% @publisher.names.each do |name| %>
  <div class="mb-3 row">
    <label class="col-sm-2 col-form-label">
      <%= tag.span(I18n.t(:name, locale_key: name.locale,
          scope: [:activerecord, :attributes, :publisher])) %>
    </label>
    <div class="col-sm-10">
      <span class="form-control-plaintext">
        <%= name.value %>
      </span>
    </div>
  </div>
<% end %>
<% @publisher.abbreviations.each do |name| %>
  <div class="mb-3 row">
    <label class="col-sm-2 col-form-label">
      <%= tag.span(I18n.t(:abbreviation, locale_key: name.locale,
          scope: [:activerecord, :attributes, :publisher])) %>
    </label>
    <div class="col-sm-10">
      <span class="form-control-plaintext">
        <%= name.value %>
      </span>
    </div>
  </div>
<% end %>
<div class="mb-3 row">
  <label class="col-sm-2 col-form-label">URL</label>
  <div class="col-sm-10">
    <span class="form-control-plaintext">
      <%= @publisher.link_to_url_tag %>
    </span>
  </div>
</div>